spring:
  datasource:
    url: jdbc:mysql://localhost:3306/easytrade_db
    username: easytrade
    password: easypassword
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
---
easytrade:
  exchange: NASDAQ
  symbols: AAPL, MSFT, GOOG, GOOGL, AMAZN, PCAR, BRK/A, BRK/B, NVDA, TSLA, META
