spring:
  datasource:
    url: jdbc:mysql://localhost:3306/easytrade_testing
    username: easytrade
    password: easypassword
  jpa:
    hibernate:
      ddl-auto: create-drop # We create and drop the database between tests.
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
---
easytrade:
  exchange: NASDAQ
  symbols: AAPL, MSFT, GOOG, GOOGL, PCAR, NVDA, TSLA, META
  starting-balance: 100_000.0